<<<<<<< HEAD
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-hacker
=======
title: My CTF writeups
description: Apoorva Saurav
url: "hcpssaurava.github.io" 
github_username:  hcpssaurava
repository: hcpssaurava/hcpssaurava.github.io
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/hacker@v0.2.0
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-hacker

>>>>>>> Fixing
